---
- hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - infoblox.nios_modules

  vars: 
    dtc:
      server_name: SERVER1
      host_ip: 10.100.1.10
      comment: Created with Ansible
      state: present
    nios_provider:
      host: "{{ nios_grid_url }}"
      username: "{{ nios_grid_username }}"
      password: "{{ nios_grid_password }}"

  tasks:
    
    - name: Create DTC Server
      infoblox.nios_modules.nios_dtc_server:
        name: "{{ dtc.server_name }}"
        host: "{{ dtc.host_ip }}"
        comment: "{{ dtc.comment }}"
        state: "{{ dtc.state }}"
        provider: "{{ nios_provider }}"